### ISSUE TITLE
Paralellization and multithreading support?

### ISSUE THREAD

**Issue by TheChymera** [moloney/dcmstack#30]
Hi, seeing how grouping/conversion takes a lot of time, and I am still unable to use `group_and_stack` via nipype, I set out to paralellize my current dcmstack/for-loop workflow.

You can see the version I am refering to right now [here](https://github.com/TheChymera/chyMRI/blob/607c1d565740aa48285b3ff1b1e0f2384be75987/functions_preprocessing.py).

Strangely, running a pool of size 2 or size 4, or 8, or 16 (4 cores on this machine), I see n marked speed improvement. Any idea why that could be? is your code already paralellizing stuff? Would `group_and_stack` (which I am not atm using) distribute its tasks over multiple threads?

**Comment by TheChymera** [comment]
@moloney ?

**Comment by moloney** [comment]
Nothing in dcmstack is parallel. You are probably mostly I/O bound, and if you are CPU bound then threads won't really help due the GIL.

If you don't need all the meta data, you could try using the `minimal_extractor` instead of the `default_extractor`.  That should speed things up considerably.

If you do want all the meta data you could try using multiprocessing to parallelize the parsing. I usually just run multiple conversions in parallel on our cluster rather than trying to speed up the conversion of a single series.

Anyway, these discussions should really happen on the nipy mailing list rather than in github issues.

**Comment by TheChymera** [comment]
@moloney it seems the nipy mailing list is no longer? and discussions should move to github?
https://groups.google.com/forum/#!topic/nipy-user/LMfhvcDgfck

**Comment by moloney** [comment]
Look here: http://mail.scipy.org/mailman/listinfo/nipy-devel
