### ISSUE TITLE
original dicom voxel order

### ISSUE THREAD

**Issue by romainVala** [moloney/dcmstack#46]
Hello

I use dcmstack to convert the dicom with the .to_nifti function with voxel_order='LAS' but I get into trouble with diffusion data to get the correct diffusion direction. So for those cases I would like to write with the same orientation as dicom.
So I put voxel_order='' and try to convert a sagital acquisition.
The voxel order I expect (and the one give by dcm2nii) is :
    [ 3 -1 2 4 ]
but I obtain with dcmstack :  [ -3 -2 -1 4 ] 
do you know why and if it is possible to make the order same as the acquisition ?

many thanks

Romain

**Comment by moloney** [comment]
I am not sure how dcm2nii produces its result, but we do skip any kind of data re-ordering when you pass `voxel_order=''`. Of course the sign of the slice direction is somewhat arbitrary since the slices are not stored in a contiguous array in a DICOM. I am pretty sure dcmstack will just choose the right-handed coordinate system in this case.

If you are convinced something else is going on here, please let me know.

**Comment by romainVala** [comment]
Hi,
You may be wright, dcm2nii may rotate the plan because there is a 90° in plane rotation between the 2 conversions. but I do not know which on is more similaire to the dicom voxel order. 
Any way my concern was to end up with diffusion direction coherent with the pixel order, since I was using dcm2nii as ground truth ...
May be the correct diffusion direction will be output in a near futur ...

**Comment by moloney** [comment]
Closing as stale / resolved.
